eureka:
   client:
      enabled: false

#logging:
#  level: INFO
  
security:
   activation:
      status: false      
   # basic auth credentials
   user:
      name: bigpi
      password: password
     
#use for admin client
management:
   security:
      enabled: false
      
  
#  datasource:
#    url: jdbc:postgresql://localhost:5432/cingulatadb
#    username: postgres
#    password: 123 
   datasource:
      url: jdbc:postgresql://10.8.34.73:5432/PatternSearch
      username: postgres
      password: bigpi!123!
    
   jpa:
      hibernate.ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
      
      
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE


#filesStorageServiceConfig:
#  fileDirStr: /home/hgnguyen/Desktop/seal/upload/


application:
   fheServerData: http://10.8.34.73:9090
   fheServerAnalysis: http://10.8.34.73:9191
   seal:
#    FilesStorageServiceImpl & FHEPatternSearchService
     sealDir: /opt/fhe/datalake/seal
#     sealDir: /opt/fhe/seal/bin/patternSearch
     dataDir: ${application.seal.sealDir}/data/
     resultDir: ${application.seal.sealDir}/result/
     uploadDir: ${application.seal.sealDir}/upload/
     keyDir: ${application.seal.sealDir}/keys/
     sample: 40
     filename: l
     patternSearchBin: /opt/fhe/seal/bin/patternSearch
     encryptPath: ${application.seal.patternSearchBin}/patternSearch_encrypt_v2
     decryptPath: ${application.seal.patternSearchBin}/patternSearch_decrypt_v2
     decrypCheckedResulttPath: ${application.seal.patternSearchBin}/patternSearch_decrypt_result_v2
     evaluatePath: ${application.seal.patternSearchBin}/patternSearch_evaluate_v2
#     keyDir: ${application.seal.patternSearchBin}/keys/

      
         